-- ============================================================
-- POS Database Schema สำหรับ Supabase
-- วิธีใช้: เปิด Supabase Dashboard > SQL Editor > วาง SQL นี้ทั้งหมดแล้วกด Run
-- ============================================================

-- หมวดหมู่สินค้า
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  position int not null default 0,
  created_at timestamptz not null default now()
);

-- สินค้า
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  barcode text,
  category_id uuid references public.categories (id) on delete set null,
  price numeric(12, 2) not null default 0,        -- ราคาขาย
  cost numeric(12, 2) not null default 0,         -- ต้นทุนต่อหน่วย
  stock numeric(12, 2) not null default 0,        -- จำนวนคงเหลือ
  track_stock boolean not null default true,      -- ตัดสต๊อกเมื่อขายหรือไม่
  low_stock_threshold numeric(12, 2) not null default 5,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products (category_id);
create index if not exists idx_products_barcode on public.products (barcode);

-- บิลขาย
create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  sale_number bigint generated by default as identity,
  subtotal numeric(12, 2) not null default 0,
  discount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  cost_total numeric(12, 2) not null default 0,   -- ต้นทุนรวมของบิล (บันทึก ณ เวลาขาย)
  payment_method text not null default 'cash',    -- cash | transfer | card
  received numeric(12, 2),                        -- เงินที่รับมา (เงินสด)
  change numeric(12, 2),                          -- เงินทอน
  note text,
  status text not null default 'completed',       -- open | completed | voided
  voided_at timestamptz,
  user_id uuid references auth.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_sales_created_at on public.sales (created_at);
create index if not exists idx_sales_status on public.sales (status);

-- รายการสินค้าในบิล (บันทึกราคา/ต้นทุน ณ เวลาขาย)
create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  product_name text not null,
  price numeric(12, 2) not null,
  cost numeric(12, 2) not null default 0,
  quantity numeric(12, 2) not null,
  total numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_sale_items_sale on public.sale_items (sale_id);
create index if not exists idx_sale_items_product on public.sale_items (product_id);

-- ============================================================
-- ระบบ role พนักงาน: owner (เจ้าของร้าน) > manager (ผู้จัดการ) > staff (พนักงานขาย)
-- ============================================================
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  phone text,
  role text not null default 'staff' check (role in ('owner', 'manager', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- สมัครคนแรกกลายเป็น owner อัตโนมัติ คนถัดไปเป็น staff (owner ปรับ role ให้ทีหลังได้)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (
    new.id,
    new.email,
    case when exists (select 1 from public.profiles) then 'staff' else 'owner' end
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ผู้ใช้ที่มีอยู่ก่อนระบบ role จะถูกตั้งเป็น owner
insert into public.profiles (id, email, role)
select id, email, 'owner' from auth.users
on conflict (id) do nothing;

-- ฟังก์ชันช่วยสำหรับ RLS (security definer กันไม่ให้ policy ของ profiles อ้างถึงตัวเองแล้ววนลูป)
create or replace function public.my_role()
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_manager_or_above()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(public.my_role() in ('owner', 'manager'), false);
$$;

create or replace function public.is_owner()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(public.my_role() = 'owner', false);
$$;

-- จำกัดสิทธิ์เรียกฟังก์ชัน helper: ห้าม anon (ผู้ไม่ล็อกอิน) เรียกได้
revoke execute on function public.my_role from public, anon;
revoke execute on function public.is_manager_or_above from public, anon;
revoke execute on function public.is_owner from public, anon;
grant execute on function public.my_role to authenticated;
grant execute on function public.is_manager_or_above to authenticated;
grant execute on function public.is_owner to authenticated;
-- handle_new_user ใช้เฉพาะภายใน trigger เท่านั้น ไม่ควรเรียกตรงได้เลย
revoke execute on function public.handle_new_user from public, anon, authenticated;

alter table public.profiles enable row level security;

drop policy if exists "read own or manager reads all" on public.profiles;
create policy "read own or manager reads all" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_manager_or_above());

drop policy if exists "owner updates roles" on public.profiles;
create policy "owner updates roles" on public.profiles
  for update to authenticated
  using (public.is_owner())
  with check (public.is_owner());

-- กันเบอร์โทรซ้ำ (NULL ซ้ำกันได้ตามปกติของ unique index)
create unique index if not exists profiles_phone_unique_idx
  on public.profiles (phone) where phone is not null;

-- ค้นหาอีเมลจากเบอร์โทร สำหรับหน้า login (เรียกได้ก่อนล็อกอิน)
-- normalize เบอร์โทรทั้งสองฝั่งให้เหลือแต่ตัวเลข กันปัญหาเว้นวรรค/ขีด
create or replace function public.get_email_by_phone(p_phone text)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select email from public.profiles
  where regexp_replace(phone, '[^0-9]', '', 'g') = regexp_replace(p_phone, '[^0-9]', '', 'g')
  limit 1;
$$;

revoke execute on function public.get_email_by_phone from public;
grant execute on function public.get_email_by_phone to anon, authenticated;

-- ============================================================
-- Row Level Security: หมวดหมู่/สินค้า — staff และ manager แก้ไขได้เท่ากัน
-- (ใช้จัดการสต๊อก/สินค้าหน้างานได้เอง) — บิลขาย/รายการขายเปิดให้พนักงานทุกคน
-- ============================================================
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

drop policy if exists "authenticated full access" on public.categories;
create policy "select categories" on public.categories
  for select to authenticated using (true);
create policy "insert categories" on public.categories
  for insert to authenticated with check (true);
create policy "update categories" on public.categories
  for update to authenticated using (true) with check (true);
create policy "delete categories" on public.categories
  for delete to authenticated using (true);

drop policy if exists "authenticated full access" on public.products;
create policy "select products" on public.products
  for select to authenticated using (true);
create policy "insert products" on public.products
  for insert to authenticated with check (true);
create policy "update products" on public.products
  for update to authenticated using (true) with check (true);
create policy "delete products" on public.products
  for delete to authenticated using (true);

drop policy if exists "authenticated full access" on public.sales;
create policy "authenticated full access" on public.sales
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access" on public.sale_items;
create policy "authenticated full access" on public.sale_items
  for all to authenticated using (true) with check (true);

-- ============================================================
-- ฟังก์ชันบันทึกการขาย: สร้างบิล + รายการ + ตัดสต๊อก ใน transaction เดียว
-- ============================================================
create or replace function public.create_sale(
  p_items jsonb,                       -- [{"product_id": "...", "quantity": 1}, ...]
  p_discount numeric default 0,
  p_payment_method text default 'cash',
  p_received numeric default null,
  p_note text default null
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale_id uuid;
  v_subtotal numeric := 0;
  v_cost_total numeric := 0;
  v_total numeric;
  v_item jsonb;
  v_product products%rowtype;
  v_qty numeric;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อนทำรายการขาย';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'ไม่มีรายการสินค้าในบิล';
  end if;

  -- รอบแรก: ล็อกแถวสินค้าและคำนวณยอดรวม
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item ->> 'quantity')::numeric;
    if v_qty is null or v_qty <= 0 then
      raise exception 'จำนวนสินค้าไม่ถูกต้อง';
    end if;
    select * into v_product from products
      where id = (v_item ->> 'product_id')::uuid
      for update;
    if not found then
      raise exception 'ไม่พบสินค้า (id: %)', v_item ->> 'product_id';
    end if;
    v_subtotal := v_subtotal + v_product.price * v_qty;
    v_cost_total := v_cost_total + v_product.cost * v_qty;
  end loop;

  v_total := greatest(v_subtotal - coalesce(p_discount, 0), 0);

  insert into sales (subtotal, discount, total, cost_total, payment_method, received, change, note, user_id)
  values (
    v_subtotal,
    coalesce(p_discount, 0),
    v_total,
    v_cost_total,
    p_payment_method,
    p_received,
    case when p_received is not null then greatest(p_received - v_total, 0) end,
    p_note,
    auth.uid()
  )
  returning id into v_sale_id;

  -- รอบสอง: บันทึกรายการและตัดสต๊อก
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item ->> 'quantity')::numeric;
    select * into v_product from products where id = (v_item ->> 'product_id')::uuid;
    insert into sale_items (sale_id, product_id, product_name, price, cost, quantity, total)
    values (v_sale_id, v_product.id, v_product.name, v_product.price, v_product.cost, v_qty, v_product.price * v_qty);
    if v_product.track_stock then
      update products set stock = stock - v_qty, updated_at = now() where id = v_product.id;
    end if;
  end loop;

  return v_sale_id;
end;
$$;

-- ============================================================
-- ฟังก์ชันยกเลิกบิล: เปลี่ยนสถานะเป็น voided และคืนสต๊อก (พนักงานทุกคนทำได้)
-- ============================================================
create or replace function public.void_sale(p_sale_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อน';
  end if;

  update sales set status = 'voided', voided_at = now()
    where id = p_sale_id and status in ('open', 'completed');
  if not found then
    raise exception 'ไม่พบบิลหรือบิลถูกยกเลิกไปแล้ว';
  end if;

  for v_item in
    select si.product_id, si.quantity from sale_items si where si.sale_id = p_sale_id
  loop
    update products set stock = stock + v_item.quantity, updated_at = now()
      where id = v_item.product_id and track_stock;
  end loop;
end;
$$;

revoke execute on function public.create_sale from public, anon;
revoke execute on function public.void_sale from public, anon;
grant execute on function public.create_sale to authenticated;
grant execute on function public.void_sale to authenticated;

-- ============================================================
-- รายจ่าย / ต้นทุน (ต้นทุนเริ่มต้น, วัตถุดิบ, ค่าเช่า, เงินเดือน ฯลฯ)
-- แยกจากต้นทุนสินค้า (products.cost) ซึ่งเป็นต้นทุนต่อชิ้นที่ขาย
-- เข้าถึงได้เฉพาะ manager ขึ้นไป (พนักงานขายเข้าไม่ได้เลย)
-- ============================================================

-- หมวดหมู่รายจ่าย
create table if not exists public.expense_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  position int not null default 0,
  created_at timestamptz not null default now()
);

-- รายจ่าย
create table if not exists public.expenses (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.expense_categories (id) on delete set null,
  title text not null,
  amount numeric(12, 2) not null default 0,
  expense_date date not null default current_date,
  note text,
  user_id uuid references auth.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_expenses_date on public.expenses (expense_date);
create index if not exists idx_expenses_category on public.expenses (category_id);

alter table public.expense_categories enable row level security;
alter table public.expenses enable row level security;

drop policy if exists "authenticated full access" on public.expense_categories;
drop policy if exists "manager full access" on public.expense_categories;
create policy "owner full access" on public.expense_categories
  for all to authenticated using (public.is_owner()) with check (public.is_owner());

drop policy if exists "authenticated full access" on public.expenses;
drop policy if exists "manager full access" on public.expenses;
create policy "owner full access" on public.expenses
  for all to authenticated using (public.is_owner()) with check (public.is_owner());

insert into public.expense_categories (name, position) values
  ('ต้นทุนเริ่มต้น/เงินลงทุน', 1),
  ('วัตถุดิบ', 2),
  ('ค่าเช่าร้าน', 3),
  ('ค่าน้ำ-ค่าไฟ', 4),
  ('เงินเดือน/ค่าแรง', 5),
  ('ค่าขนส่ง', 6),
  ('การตลาด/โฆษณา', 7),
  ('อื่นๆ', 8)
on conflict (name) do nothing;

-- ============================================================
-- รายได้อื่นๆ นอกเหนือจากยอดขาย POS (ซึ่งนับอัตโนมัติอยู่แล้ว)
-- เข้าถึงได้เฉพาะ owner เท่านั้นเช่นเดียวกับรายจ่าย
-- ============================================================
create table if not exists public.income_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  position int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.income (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.income_categories (id) on delete set null,
  title text not null,
  amount numeric(12, 2) not null default 0,
  income_date date not null default current_date,
  note text,
  user_id uuid references auth.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_income_date on public.income (income_date);
create index if not exists idx_income_category on public.income (category_id);

alter table public.income_categories enable row level security;
alter table public.income enable row level security;

drop policy if exists "manager full access" on public.income_categories;
create policy "owner full access" on public.income_categories
  for all to authenticated using (public.is_owner()) with check (public.is_owner());

drop policy if exists "manager full access" on public.income;
create policy "owner full access" on public.income
  for all to authenticated using (public.is_owner()) with check (public.is_owner());

insert into public.income_categories (name, position) values
  ('รายได้จากการขายอื่นๆ', 1),
  ('เงินลงทุนเพิ่ม', 2),
  ('รายได้ค่าบริการ', 3),
  ('เงินคืน/ส่วนลดจากซัพพลายเออร์', 4),
  ('รายได้อื่นๆ', 5)
on conflict (name) do nothing;

-- ============================================================
-- ข้อมูลตัวอย่าง (ลบส่วนนี้ออกได้ถ้าไม่ต้องการ)
-- ============================================================
insert into public.categories (name, position) values
  ('เครื่องดื่ม', 1),
  ('อาหาร', 2),
  ('ขนม', 3)
on conflict do nothing;

-- ============================================================
-- โต๊ะ + บิลต่อโต๊ะ (กินก่อนจ่ายทีหลัง)
-- ============================================================
create table if not exists public.dining_tables (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  position int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.dining_tables enable row level security;

drop policy if exists "select tables" on public.dining_tables;
create policy "select tables" on public.dining_tables
  for select to authenticated using (true);
drop policy if exists "owner insert tables" on public.dining_tables;
create policy "owner insert tables" on public.dining_tables
  for insert to authenticated with check (public.is_owner());
drop policy if exists "owner update tables" on public.dining_tables;
create policy "owner update tables" on public.dining_tables
  for update to authenticated using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner delete tables" on public.dining_tables;
create policy "owner delete tables" on public.dining_tables
  for delete to authenticated using (public.is_owner());

-- บิลผูกกับโต๊ะได้ (null = ขายด่วน/ไม่นั่งโต๊ะ) และมีสถานะ "open" เพิ่มเข้ามา
alter table public.sales add column if not exists table_id uuid references public.dining_tables (id) on delete set null;
create index if not exists idx_sales_table_open on public.sales (table_id) where status = 'open';

alter table public.sales drop constraint if exists sales_status_check;
alter table public.sales add constraint sales_status_check check (status in ('open', 'completed', 'voided'));

-- เพิ่มออเดอร์เข้าโต๊ะ: สร้างบิลใหม่ถ้าโต๊ะว่าง หรือรวมเข้าบิล "open" เดิมถ้ามีอยู่แล้ว
create or replace function public.add_order_to_table(
  p_table_id uuid,
  p_items jsonb
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale_id uuid;
  v_item jsonb;
  v_product products%rowtype;
  v_qty numeric;
  v_line_total numeric;
  v_line_cost numeric;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อน';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'ไม่มีรายการสินค้า';
  end if;

  select id into v_sale_id from sales
    where table_id = p_table_id and status = 'open'
    limit 1;

  if v_sale_id is null then
    insert into sales (table_id, subtotal, total, cost_total, payment_method, status, user_id)
    values (p_table_id, 0, 0, 0, 'cash', 'open', auth.uid())
    returning id into v_sale_id;
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item ->> 'quantity')::numeric;
    if v_qty is null or v_qty <= 0 then
      raise exception 'จำนวนสินค้าไม่ถูกต้อง';
    end if;

    select * into v_product from products
      where id = (v_item ->> 'product_id')::uuid
      for update;
    if not found then
      raise exception 'ไม่พบสินค้า (id: %)', v_item ->> 'product_id';
    end if;

    v_line_total := v_product.price * v_qty;
    v_line_cost := v_product.cost * v_qty;

    insert into sale_items (sale_id, product_id, product_name, price, cost, quantity, total)
    values (v_sale_id, v_product.id, v_product.name, v_product.price, v_product.cost, v_qty, v_line_total);

    if v_product.track_stock then
      update products set stock = stock - v_qty, updated_at = now() where id = v_product.id;
    end if;

    update sales set
      subtotal = subtotal + v_line_total,
      total = greatest(subtotal + v_line_total - discount, 0),
      cost_total = cost_total + v_line_cost
      where id = v_sale_id;
  end loop;

  return v_sale_id;
end;
$$;

-- เก็บเงิน/ปิดโต๊ะ: ปิดบิล "open" เป็น "completed" พร้อมรับส่วนลด/วิธีชำระ/เงินรับ
create or replace function public.checkout_table(
  p_sale_id uuid,
  p_discount numeric default 0,
  p_payment_method text default 'cash',
  p_received numeric default null,
  p_note text default null
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subtotal numeric;
  v_total numeric;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อน';
  end if;

  select subtotal into v_subtotal from sales where id = p_sale_id and status = 'open';
  if not found then
    raise exception 'ไม่พบบิลที่เปิดอยู่ของโต๊ะนี้';
  end if;

  v_total := greatest(v_subtotal - coalesce(p_discount, 0), 0);

  update sales set
    discount = coalesce(p_discount, 0),
    total = v_total,
    payment_method = p_payment_method,
    received = p_received,
    change = case when p_received is not null then greatest(p_received - v_total, 0) end,
    note = p_note,
    status = 'completed'
    where id = p_sale_id;
end;
$$;

revoke execute on function public.add_order_to_table from public, anon;
revoke execute on function public.checkout_table from public, anon;
grant execute on function public.add_order_to_table to authenticated;
grant execute on function public.checkout_table to authenticated;

insert into public.dining_tables (name, position) values
  ('โต๊ะ 1', 1), ('โต๊ะ 2', 2), ('โต๊ะ 3', 3), ('โต๊ะ 4', 4), ('โต๊ะ 5', 5)
on conflict do nothing;
