-- ============================================================
-- POS Database Schema สำหรับ Supabase
-- วิธีใช้: เปิด Supabase Dashboard > SQL Editor > วาง SQL นี้ทั้งหมดแล้วกด Run
-- ============================================================

-- หมวดหมู่สินค้า
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  position int not null default 0,
  created_at timestamptz not null default now()
);

-- สินค้า
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  barcode text,
  category_id uuid references public.categories (id) on delete set null,
  price numeric(12, 2) not null default 0,        -- ราคาขาย
  cost numeric(12, 2) not null default 0,         -- ต้นทุนต่อหน่วย
  stock numeric(12, 2) not null default 0,        -- จำนวนคงเหลือ
  track_stock boolean not null default true,      -- ตัดสต๊อกเมื่อขายหรือไม่
  low_stock_threshold numeric(12, 2) not null default 5,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products (category_id);
create index if not exists idx_products_barcode on public.products (barcode);

-- บิลขาย
create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  sale_number bigint generated by default as identity,
  subtotal numeric(12, 2) not null default 0,
  discount numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  cost_total numeric(12, 2) not null default 0,   -- ต้นทุนรวมของบิล (บันทึก ณ เวลาขาย)
  payment_method text not null default 'cash',    -- cash | transfer | card
  received numeric(12, 2),                        -- เงินที่รับมา (เงินสด)
  change numeric(12, 2),                          -- เงินทอน
  note text,
  status text not null default 'completed',       -- completed | voided
  voided_at timestamptz,
  user_id uuid references auth.users (id),
  created_at timestamptz not null default now()
);

create index if not exists idx_sales_created_at on public.sales (created_at);
create index if not exists idx_sales_status on public.sales (status);

-- รายการสินค้าในบิล (บันทึกราคา/ต้นทุน ณ เวลาขาย)
create table if not exists public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales (id) on delete cascade,
  product_id uuid references public.products (id) on delete set null,
  product_name text not null,
  price numeric(12, 2) not null,
  cost numeric(12, 2) not null default 0,
  quantity numeric(12, 2) not null,
  total numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_sale_items_sale on public.sale_items (sale_id);
create index if not exists idx_sale_items_product on public.sale_items (product_id);

-- ============================================================
-- Row Level Security: ทุกคนที่ล็อกอินแล้ว (พนักงานร้าน) ใช้ข้อมูลร่วมกัน
-- ============================================================
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

drop policy if exists "authenticated full access" on public.categories;
create policy "authenticated full access" on public.categories
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access" on public.products;
create policy "authenticated full access" on public.products
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access" on public.sales;
create policy "authenticated full access" on public.sales
  for all to authenticated using (true) with check (true);

drop policy if exists "authenticated full access" on public.sale_items;
create policy "authenticated full access" on public.sale_items
  for all to authenticated using (true) with check (true);

-- ============================================================
-- ฟังก์ชันบันทึกการขาย: สร้างบิล + รายการ + ตัดสต๊อก ใน transaction เดียว
-- ============================================================
create or replace function public.create_sale(
  p_items jsonb,                       -- [{"product_id": "...", "quantity": 1}, ...]
  p_discount numeric default 0,
  p_payment_method text default 'cash',
  p_received numeric default null,
  p_note text default null
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale_id uuid;
  v_subtotal numeric := 0;
  v_cost_total numeric := 0;
  v_total numeric;
  v_item jsonb;
  v_product products%rowtype;
  v_qty numeric;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อนทำรายการขาย';
  end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then
    raise exception 'ไม่มีรายการสินค้าในบิล';
  end if;

  -- รอบแรก: ล็อกแถวสินค้าและคำนวณยอดรวม
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item ->> 'quantity')::numeric;
    if v_qty is null or v_qty <= 0 then
      raise exception 'จำนวนสินค้าไม่ถูกต้อง';
    end if;
    select * into v_product from products
      where id = (v_item ->> 'product_id')::uuid
      for update;
    if not found then
      raise exception 'ไม่พบสินค้า (id: %)', v_item ->> 'product_id';
    end if;
    v_subtotal := v_subtotal + v_product.price * v_qty;
    v_cost_total := v_cost_total + v_product.cost * v_qty;
  end loop;

  v_total := greatest(v_subtotal - coalesce(p_discount, 0), 0);

  insert into sales (subtotal, discount, total, cost_total, payment_method, received, change, note, user_id)
  values (
    v_subtotal,
    coalesce(p_discount, 0),
    v_total,
    v_cost_total,
    p_payment_method,
    p_received,
    case when p_received is not null then greatest(p_received - v_total, 0) end,
    p_note,
    auth.uid()
  )
  returning id into v_sale_id;

  -- รอบสอง: บันทึกรายการและตัดสต๊อก
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := (v_item ->> 'quantity')::numeric;
    select * into v_product from products where id = (v_item ->> 'product_id')::uuid;
    insert into sale_items (sale_id, product_id, product_name, price, cost, quantity, total)
    values (v_sale_id, v_product.id, v_product.name, v_product.price, v_product.cost, v_qty, v_product.price * v_qty);
    if v_product.track_stock then
      update products set stock = stock - v_qty, updated_at = now() where id = v_product.id;
    end if;
  end loop;

  return v_sale_id;
end;
$$;

-- ============================================================
-- ฟังก์ชันยกเลิกบิล: เปลี่ยนสถานะเป็น voided และคืนสต๊อก
-- ============================================================
create or replace function public.void_sale(p_sale_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
begin
  if auth.uid() is null then
    raise exception 'ต้องล็อกอินก่อน';
  end if;

  update sales set status = 'voided', voided_at = now()
    where id = p_sale_id and status = 'completed';
  if not found then
    raise exception 'ไม่พบบิลหรือบิลถูกยกเลิกไปแล้ว';
  end if;

  for v_item in
    select si.product_id, si.quantity from sale_items si where si.sale_id = p_sale_id
  loop
    update products set stock = stock + v_item.quantity, updated_at = now()
      where id = v_item.product_id and track_stock;
  end loop;
end;
$$;

revoke execute on function public.create_sale from public, anon;
revoke execute on function public.void_sale from public, anon;
grant execute on function public.create_sale to authenticated;
grant execute on function public.void_sale to authenticated;

-- ============================================================
-- ข้อมูลตัวอย่าง (ลบส่วนนี้ออกได้ถ้าไม่ต้องการ)
-- ============================================================
insert into public.categories (name, position) values
  ('เครื่องดื่ม', 1),
  ('อาหาร', 2),
  ('ขนม', 3)
on conflict do nothing;
